version: "3"
services:
  master:
    restart: always
    container_name: drone-ci_master
    image: drone/drone:latest
    networks:
      - apps
      - drone-runners
    volumes:
      - data:/data
    environment:
      - "DRONE_DATABASE_DRIVER=sqlite3"
      - "DRONE_DATABASE_DATASOURCE=/data/database.sqlite"
      - "DRONE_SERVER_PORT=:80"
      - "DRONE_SERVER_HOST=drone.dome.lesha.co"
      - "DRONE_DATADOG_ENABLED=true"
      - "DRONE_DATADOG_ENDPOINT=https://stats.drone.ci/api/v1/series"
      - "DRONE_SERVER_PROTO=https"
      - "DRONE_RPC_SECRET=correct-horse-batter-staple"
      - "DRONE_GOGS_SERVER=https://git.dome.lesha.co"
      - "DRONE_USER_CREATE=username:lesha,admin:true"

  runner-docker:
    restart: always
    container_name: drone-ci_runner-docker
    image: drone/drone-runner-docker:latest
    networks:
      - drone-runners
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - "DRONE_RPC_PROTO=http"
      - "DRONE_RPC_HOST=drone-ci_master"
      - "DRONE_RPC_SECRET=correct-horse-batter-staple"
      - "DRONE_RUNNER_CAPACITY=2"
      - "DRONE_RUNNER_NAME=drone-runner-docker"

volumes:
  data:
networks:
  drone-runners:
  apps:
    external: true
