version: "3"
name: nas
services:
  drone-master:
    restart: always
    image: drone/drone:latest
    networks:
      - apps
      - drone-runners
    volumes:
      - drone:/data
    environment:
      - "DRONE_DATABASE_DRIVER=sqlite3"
      - "DRONE_DATABASE_DATASOURCE=/data/database.sqlite"
      - "DRONE_SERVER_PORT=:80"
      - "DRONE_SERVER_HOST=drone.dome.lesha.co"
      - "DRONE_DATADOG_ENABLED=true"
      - "DRONE_DATADOG_ENDPOINT=https://stats.drone.ci/api/v1/series"
      - "DRONE_SERVER_PROTO=https"
      - "DRONE_RPC_SECRET=correct-horse-batter-staple"
      - "DRONE_GOGS_SERVER=https://git.dome.lesha.co"
      - "DRONE_USER_CREATE=username:lesha,admin:true"
  drone-runner:
    restart: always
    image: drone/drone-runner-docker:latest
    networks:
      - drone-runners
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - "DRONE_RPC_PROTO=http"
      - "DRONE_RPC_HOST=drone-ci_master"
      - "DRONE_RPC_SECRET=correct-horse-batter-staple"
      - "DRONE_RUNNER_CAPACITY=2"
      - "DRONE_RUNNER_NAME=drone-runner-docker"
  vaultwarden:
    restart: always
    image: vaultwarden/server:latest
    networks:
      - apps
    volumes:
      - vaultwarden:/data
    environment:
      - "WEBSOCKET_ENABLED=true"
      - "DOMAIN=https://vw.dome.lesha.co"
  # gitea:


volumes:
  drone:
  vaultwarden:
networks:
  drone-runners:
  apps:
    # this will not be external once i pull nginx in this configuration
    external: true
