name: "nas"
services:
  keycloak:
    image: quay.io/keycloak/keycloak
    ports: 
      - 8080:8080
    networks:
      - db
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: keycloak
      KC_DB_USERNAME: keycloak_user # DB_KEYCLOAK_USERNAME
      KC_DB_PASSWORD: keycloak # DB_KEYCLOAK_PASSWORD
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak # DB_KEYCLOAK_DBNAME

      KC_HOSTNAME_STRICT: false
    command:
      - start-dev
    depends_on: 
      - postgres
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - db 
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres

  gitea:
    image: gitea/gitea:1.18.5
    environment:
      GITEA__database__DB_TYPE: postgres
      GITEA__database__HOST: postgres
      GITEA__database__NAME: gitea #DB_GITEA_DBNAME
      GITEA__database__USER: gitea_user #DB_GITEA_USERNAME
      GITEA__database__PASSWD: gitea #DB_GITEA_PASSWORD
    restart: always
    networks:
      - db
    volumes:
      - gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - postgres
    ports:
      - "3000:3000"
      - "222:22"
volumes:
  pgdata:
  gitea:

networks:
  apps: 
  db:

  # drone-master:
  #   image: drone/drone:latest
  #   networks:
  #     - apps
  #   environment:
  #     - "DRONE_DATABASE_DRIVER=sqlite3"
  #     - "DRONE_DATABASE_DATASOURCE=/data/database.sqlite"
  #     - "DRONE_SERVER_PORT=:80"
  #     - "DRONE_SERVER_HOST=drone.dome.lesha.co"
  #     - "DRONE_DATADOG_ENABLED=true"
  #     - "DRONE_DATADOG_ENDPOINT=https://stats.drone.ci/api/v1/series"
  #     - "DRONE_SERVER_PROTO=https"
  #     - "DRONE_RPC_SECRET=correct-horse-batter-staple"
  #     - "DRONE_GOGS_SERVER=https://git.dome.lesha.co"
  #     - "DRONE_USER_CREATE=username:lesha,admin:true"

  # drone-runner:
  #   container_name: drone-ci_runner-docker
  #   image: drone/drone-runner-docker:latest
  #   networks:
  #     - apps
    
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   environment:
  #     - "DRONE_RPC_PROTO=http"
  #     - "DRONE_RPC_HOST=drone-ci_master"
  #     - "DRONE_RPC_SECRET=correct-horse-batter-staple"
  #     - "DRONE_RUNNER_CAPACITY=2"
  #     - "DRONE_RUNNER_NAME=drone-runner-docker"
    # jellyfin:
    # transmission:
    # vaultwarden
    # vscode:
    # web-frontend:
    
    # photos?:
    # drive?:

    #   frontend:
    #     networks:
    #       - front-tier
    #       - back-tier
    #     configs:
    #       - httpd-config
    #     secrets:
    #       - server-certificate
    #     volumes:
    #       - db-data:/etc/data

    # volumes:
    #   db-data:
    #     driver: flocker
    #     driver_opts:
    #       size: "10GiB"

    # configs:
    #   httpd-config:
    #     external: true

    # secrets:
    #   server-certificate:
    #     external: true
