name: "nas"

services:
  keycloak:
    image: quay.io/keycloak/keycloak
    ports: 
      - 8080:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: 123
      KC_DB: postgres 
      KC_DB_URL: jdbc:postgresql://postgres/keycloak
    command:
      - start-dev
  postgres:
    image: postgres
    restart: always
    ports:
      - 2345:2345
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres
      PGPORT: 2345
  # drone-master:
  #   image: drone/drone:latest
  #   networks:
  #     - apps
  #   environment:
  #     - "DRONE_DATABASE_DRIVER=sqlite3"
  #     - "DRONE_DATABASE_DATASOURCE=/data/database.sqlite"
  #     - "DRONE_SERVER_PORT=:80"
  #     - "DRONE_SERVER_HOST=drone.dome.lesha.co"
  #     - "DRONE_DATADOG_ENABLED=true"
  #     - "DRONE_DATADOG_ENDPOINT=https://stats.drone.ci/api/v1/series"
  #     - "DRONE_SERVER_PROTO=https"
  #     - "DRONE_RPC_SECRET=correct-horse-batter-staple"
  #     - "DRONE_GOGS_SERVER=https://git.dome.lesha.co"
  #     - "DRONE_USER_CREATE=username:lesha,admin:true"

  # drone-runner:
  #   container_name: drone-ci_runner-docker
  #   image: drone/drone-runner-docker:latest
  #   networks:
  #     - apps
    
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   environment:
  #     - "DRONE_RPC_PROTO=http"
  #     - "DRONE_RPC_HOST=drone-ci_master"
  #     - "DRONE_RPC_SECRET=correct-horse-batter-staple"
  #     - "DRONE_RUNNER_CAPACITY=2"
  #     - "DRONE_RUNNER_NAME=drone-runner-docker"
    # gitea:
    # jellyfin:
    # transmission:
    # vaultwarden
    # vscode:
    # web-frontend:
    
    # photos?:
    # drive?:

    #   frontend:
    #     networks:
    #       - front-tier
    #       - back-tier
    #     configs:
    #       - httpd-config
    #     secrets:
    #       - server-certificate
    #     volumes:
    #       - db-data:/etc/data

    # volumes:
    #   db-data:
    #     driver: flocker
    #     driver_opts:
    #       size: "10GiB"

    # configs:
    #   httpd-config:
    #     external: true

    # secrets:
    #   server-certificate:
    #     external: true

networks:
  apps: 